In [1]:
!pip install transformers


In [2]:
import torch
from transformers import BertTokenizer, BertModel
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [3]:


# Load pre-trained BERT model and tokenizer
bert_model_name = 'bert-base-uncased'
tokenizer = BertTokenizer.from_pretrained(bert_model_name)
model = BertModel.from_pretrained(bert_model_name)

def get_bert_embeddings(texts, tokenizer, model):
    """
    Generate BERT embeddings for given texts.

    Args:
    texts (list of str): List of input texts.
    tokenizer (BertTokenizer): BERT tokenizer.
    model (BertModel): Pre-trained BERT model.

    Returns:
    np.array: Array of embeddings for each text.
    """
    embeddings = []
    for text in texts:
        # Tokenize input text and get input IDs and attention masks
        inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True, max_length=128)
        input_ids = inputs['input_ids']
        attention_mask = inputs['attention_mask']
        print(input_ids)
        print(attention_mask)

        # Generate embeddings using BERT model
        with torch.no_grad():
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            last_hidden_state = outputs.last_hidden_state

        # Take the mean of all token embeddings to get a single embedding for the text
        text_embedding = last_hidden_state.mean(dim=1).squeeze().numpy()
        embeddings.append(text_embedding)

    return np.array(embeddings)

# Sample data
texts = ["I love machine learning", "Deep learning is fascinating"]

# Get BERT embeddings
bert_embeddings = get_bert_embeddings(texts, tokenizer, model)



/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

tensor([[ 101, 1045, 2293, 3698, 4083,  102]])
tensor([[1, 1, 1, 1, 1, 1]])
tensor([[  101,  2784,  4083,  2003, 17160,   102]])
tensor([[1, 1, 1, 1, 1, 1]])


In [6]:
bert_embeddings

array([[ 0.4695494 ,  0.22903974,  0.00931859, ..., -0.00642541,
         0.17831643,  0.14607446],
       [ 0.08597799,  0.00498683,  0.01528762, ...,  0.15315264,
        -0.06141001,  0.07575808]], dtype=float32)